<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="ListenerSuite" duration-ms="244" started-at="2019-05-13T08:04:05Z" finished-at="2019-05-13T08:04:05Z">
    <groups>
    </groups>
    <test name="ListenerDemo1" duration-ms="244" started-at="2019-05-13T08:04:05Z" finished-at="2019-05-13T08:04:05Z">
      <class name="POM.TestForListenerDemo">
        <test-method status="FAIL" signature="FailTest()[pri:0, instance:POM.TestForListenerDemo@23223dd8]" name="FailTest" duration-ms="13" started-at="2019-05-13T13:34:05Z" finished-at="2019-05-13T13:34:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Paresh Rawal] but found [Akshay Kumar]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Paresh Rawal] but found [Akshay Kumar]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at POM.TestForListenerDemo.FailTest(TestForListenerDemo.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FailTest -->
        <test-method status="PASS" signature="PassTest()[pri:0, instance:POM.TestForListenerDemo@23223dd8]" name="PassTest" duration-ms="2" started-at="2019-05-13T13:34:05Z" finished-at="2019-05-13T13:34:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PassTest -->
        <test-method status="PASS" signature="Pass2Test()[pri:0, instance:POM.TestForListenerDemo@23223dd8]" name="Pass2Test" duration-ms="2" started-at="2019-05-13T13:34:05Z" depends-on-methods="POM.TestForListenerDemo.PassTest" finished-at="2019-05-13T13:34:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Pass2Test -->
        <test-method status="SKIP" signature="SkipTest()[pri:0, instance:POM.TestForListenerDemo@23223dd8]" name="SkipTest" duration-ms="0" started-at="2019-05-13T13:34:05Z" depends-on-methods="POM.TestForListenerDemo.FailTest" finished-at="2019-05-13T13:34:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestForListenerDemo.SkipTest()[pri:0, instance:POM.TestForListenerDemo@23223dd8] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestForListenerDemo.SkipTest()[pri:0, instance:POM.TestForListenerDemo@23223dd8] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SkipTest -->
        <test-method status="FAIL" signature="SkipTest2()[pri:0, instance:POM.TestForListenerDemo@23223dd8]" name="SkipTest2" duration-ms="1" started-at="2019-05-13T13:34:05Z" depends-on-methods="POM.TestForListenerDemo.PassTest" finished-at="2019-05-13T13:34:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Frog] but found [Prince]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Frog] but found [Prince]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at POM.TestForListenerDemo.SkipTest2(TestForListenerDemo.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SkipTest2 -->
      </class> <!-- POM.TestForListenerDemo -->
    </test> <!-- ListenerDemo1 -->
  </suite> <!-- ListenerSuite -->
</testng-results>
